### PR TITLE
🐛 Job Board: Fix the search form appearance

### LINKED ISSUE #127: 🐛 Job Board: Fix enum labels
As a result of #83 In the Preference model, In the yearsOfExperience and workSchedule TextChoices, the labels aren't set to the values which creates an appearance error.

Screenshot of the bug:

### PR DESCRIPTION
**Pull request by DeanBiton**
- Fixed the issue by setting the labels in the Preference model enums.
- Screenshot of the fix:

Close #127

### CODE REVIEW

**Review by Yarboa — COMMENTED** [review]
@paOmer Are there tests covers the changes? 
In case yes please add reference to the codein initial comment.

If not add a test

**Comment by DeanBiton** [comment]
@Yarboa This PR handles more of a visual error in the HTML that is created by Django. I thought that screenshotting the wanted result will suffice, should I check in the test that HTML simply contains the wanted result?

**Comment by Yarboa** [comment]
> > @paOmer Are there tests covers the changes? In case yes please add reference to the codein initial comment.
> > If not add a test
> 
> @Yarboa This PR handles more of a visual error in the HTML that is created by Django. I thought that screenshotting the wanted result will suffice, should I check in a test that the HTML file simply contains the wanted result?

Do you think there is client a client test cover this part? 
If not please add a test, else add a link to tests in main branch

**Comment by Yarboa** [comment]
> > > @paOmer Are there tests covers the changes? In case yes please add reference to the codein initial comment.
> > > If not add a test
> > 
> > 
> > @Yarboa This PR handles more of a visual error in the HTML that is created by Django. I thought that screenshotting the wanted result will suffice, should I check in a test that the HTML file simply contains the wanted result?
> 
> Do you think there is client a client test cover this part? If not please add a test, else add a link to tests in main branch

No reply from you here, in case you do not understand, please contact in slack

**Comment by DeanBiton** [comment]
> > > > @paOmer Are there tests covers the changes? In case yes please add reference to the codein initial comment.
> > > > If not add a test
> > > 
> > > 
> > > @Yarboa This PR handles more of a visual error in the HTML that is created by Django. I thought that screenshotting the wanted result will suffice, should I check in a test that the HTML file simply contains the wanted result?
> > 
> > 
> > Do you think there is client a client test cover this part? If not please add a test, else add a link to tests in main branch
> 
> No reply from you here, in case you do not understand, please contact in slack

@Yarboa The client tests are located in the #122 PR, so for now there are no tests in the main branch.

**Comment by Yarboa** [comment]
> > > > > @paOmer Are there tests covers the changes? In case yes please add reference to the codein initial comment.
> > > > > If not add a test
> > > > 
> > > > 
> > > > @Yarboa This PR handles more of a visual error in the HTML that is created by Django. I thought that screenshotting the wanted result will suffice, should I check in a test that the HTML file simply contains the wanted result?
> > > 
> > > 
> > > Do you think there is client a client test cover this part? If not please add a test, else add a link to tests in main branch
> > 
> > 
> > No reply from you here, in case you do not understand, please contact in slack
> 
> @Yarboa The client tests are located in the #122 PR, so for now there are no tests in the main branch.

Thanks, in that case i recommend to finish PR 122, you have more to do with tests over there, please refer my latest comments

**Review by Yarboa — APPROVED** [review]
LGTM

**Pull request merged**
