### PR TITLE
🚀 Feed: initializing app and adding data models

### LINKED ISSUE #26: 🚀  Adding a Feature: Feed
Create a feed, the feed is the project main page, it would contain posts from different users.
The feed app will contain posts and comments data models that need to be set up.
The following tasks should be completed:

- [x] Create a feed app
- [x] Create a post data model
- [x] Create a comment data model
- [x] Add test for the data models
- [x] Populate the DB

The post and comment data models should look like the following ERD:

[](https://mermaid.live/edit#pako:eNqtVNtuozAQ_ZWRn7pS8wN5qxKyqnqLklT7ggQODMVd44lss90q4d87NqSlt5eoCIHxmTlzOWP2oqASxVSgnSv5YGWTGuDrfp2s4HCYTGgPy7v1BqbwZJVH18P9MwL7fh0u560yD3A5h-UVpOI3GrTSY8k7qfhktrNYoUVToMvYZRFcctNqnYOqwNfKAd-GPEh4pO2EKjYf82yJNErDVhnjWcSZg53zSmqHOZOggfxdoDIPrH2cL5KSra_JvuZz75jyffazWtqFQl2CV17jGzDnUjeqwR4s-SvbkQvlpyJgQBWEDQ4z5tvgf9-7FGQ8Gv8GhegX1spn0OovOubRyvnA0zLi4KmmiJSh0Mh9JO5GAg0qzu5ubpLbIGQt3Rgmhg-wXCWLZJXczpI1m6Si4ai1_IdwdhRjyfyhdyM1fh3jDeQnz0JBTcOlZztpw-vDOMgt9_mLAeKEPnr8qVnpPt-BE-LSGCxCdE8nif6z2nafDlFHUaPry6vY_leF-o2T2xrG5LuyOnEuGrSNVCUf_xgiFTxHDbc6DECJlWx1nKhg2u5C1UmpPFkxjefrXHDjaP1sCjH1tsWj0fAjGay6F9oaX1M)

### PR DESCRIPTION
**Pull request by paOmer**
This PR is built upon issue #26 
Setting up the feed app and adding data models.

- Created the feed app
- Created a Post data model
- Created a Comment data model
- Register the data models to the admin panel
- Add tests
- Populate the DB

Close #26

### CODE REVIEW

**Review by Yarboa — COMMENTED** [review]
I would advise not to focus the GUI, for now concentrate the model
Please remove UI parts

**Review by Yarboa — COMMENTED** [review]
Please consider split the models to different files, 
This to avoid conflicts on changes occurs among different models

Consider using model directory for all the relevant classes underneath
Idea to start searching in Google :)
https://www.oreilly.com/library/view/django-design-patterns/9781788831345/88b2a9a5-a3d5-49d2-bc90-1819f89329ae.xhtml


One more thing, please add test files into the migration dirs,
Please populate the dbs with ciontent 
similar to tool introduction challenge with django

**Comment by Yarboa** [comment]
./feed/models/__init__.py:1:1: F401 '.post.Post' imported but unused
./feed/models/__init__.py:1:1: F401 '.post.PostManager' imported but unused
./feed/models/__init__.py:2:1: F401 '.comment.Comment' imported but unused
Error: Process completed with exit code 1.

Please fix flake8 errors, no review on failed actions

**Review by Yarboa — COMMENTED** [review]
Please rebase -> push
Missing:
* tests for the models already exist
* add data migrations
Please refer this https://docs.djangoproject.com/en/4.0/topics/migrations/#data-migrations-1

**Review by Yarboa — COMMENTED** [review]
Please rebase -> push
Missing:
* tests for the models already exist
Add/Update/Delete Post
Add/Update/Delete Comment
* add data migrations
Please refer this https://docs.djangoproject.com/en/4.0/topics/migrations/#data-migrations-1

**Comment by DeanBiton** [comment]
Tests look solid, I also focused on the creation and deletion of data.
Notice that you can also use the @pytest.mark.django_db() mark above a class and it will be relevant for the methods inside it.

**Comment by paOmer** [comment]
> Tests look solid, I also focused on the creation and deletion of data. Notice that you can also use the @pytest.mark.django_db() mark above a class and it will be relevant for the methods inside it.

Cool, Thanks for reviewing :)

**Comment by paOmer** [comment]
I've populated the DB and added tests to the data models.
I needed to populated the DB with preferences which made a job_board test to fail so I changed the deletion tests to delete the specific fixture models and not delete by filters.

Im not sure if the changes I made to the job board are legitimate, so please review it @DeanBiton

**Review by Yarboa — APPROVED** [review]
Please consider split the models to different files, 
This to avoid conflicts on changes occurs among different models

Consider using model directory for all the relevant classes underneath
Idea to start searching in Google :)
https://www.oreilly.com/library/view/django-design-patterns/9781788831345/88b2a9a5-a3d5-49d2-bc90-1819f89329ae.xhtml

**Comment by taljacob2** [comment]
@paOmer 
When I ran `vagrant up`, I got at the bottom of the output:

```
    default:   Your models in app(s): 'feed' have changes that are not yet reflected in a migration, and so won't be applied.
    default:   Run 'manage.py makemigrations' to make new migrations, and then re-run 'manage.py migrate' to apply them.
    default: + setsid pipenv run python manage.py runserver 0.0.0.0:8000
```

So I ran:
```
pipenv run manage.py makemigrations feed
```
and a new file called `feed/migrations/0012_alter_post_prefernces.py` was created, according to the output:
```
Migrations for 'feed':
  feed/migrations/0012_alter_post_prefernces.py
    - Alter field prefernces on post
```
and the content of the `feed/migrations/0012_alter_post_prefernces.py` file is:

```py
# Generated by Django 4.0.3 on 2022-03-30 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job_board', '0004_test_data_years_of_experiences'),
        ('feed', '0011_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='prefernces',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='job_board.preference'),
        ),
    ]

```

Is this alright? Do you know this?

**Comment by paOmer** [comment]
> @paOmer When I ran `vagrant up`, I got at the bottom of the output:
> 
> ```
>     default:   Your models in app(s): 'feed' have changes that are not yet reflected in a migration, and so won't be applied.
>     default:   Run 'manage.py makemigrations' to make new migrations, and then re-run 'manage.py migrate' to apply them.
>     default: + setsid pipenv run python manage.py runserver 0.0.0.0:8000
> ```
> 
> So I ran:
> 
> ```
> pipenv run manage.py makemigrations feed
> ```
> 
> and a new file called `feed/migrations/0012_alter_post_prefernces.py` was created, according to the output:
> 
> ```
> Migrations for 'feed':
>   feed/migrations/0012_alter_post_prefernces.py
>     - Alter field prefernces on post
> ```
> 
> and the content of the `feed/migrations/0012_alter_post_prefernces.py` file is:
> 
> ```python
> # Generated by Django 4.0.3 on 2022-03-30 06:32
> 
> from django.db import migrations, models
> import django.db.models.deletion
> 
> 
> class Migration(migrations.Migration):
> 
>     dependencies = [
>         ('job_board', '0004_test_data_years_of_experiences'),
>         ('feed', '0011_comments'),
>     ]
> 
>     operations = [
>         migrations.AlterField(
>             model_name='post',
>             name='prefernces',
>             field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='job_board.preference'),
>         ),
>     ]
> ```
> 
> Is this alright? Do you know this?

@taljacob2 thanks for letting me know.

That weird, Iv'e destroyed my VM and deleted the db file, the ran `vagrant up` but didn't got the output that you've got.
Anyway I ran `pipenv run python manage.py makemigrations` and also got the same migration file as you did.
I also ran `pipenv run python manage.py migrate` and everything seems to work find before and after this migration,
I mean that I can see that the post model has the preference model linked to it via the admin panel before and after the migration.

I guess everything seems fine, and I'm wondering if this needs to be commited to repo, what are your thoughts about it?

**Comment by taljacob2** [comment]
> > @paOmer When I ran `vagrant up`, I got at the bottom of the output:
> > 
> > ```
> >     default:   Your models in app(s): 'feed' have changes that are not yet reflected in a migration, and so won't be applied.
> >     default:   Run 'manage.py makemigrations' to make new migrations, and then re-run 'manage.py migrate' to apply them.
> >     default: + setsid pipenv run python manage.py runserver 0.0.0.0:8000
> > ```
> > 
> > So I ran:
> > 
> > ```
> > pipenv run manage.py makemigrations feed
> > ```
> > 
> > and a new file called `feed/migrations/0012_alter_post_prefernces.py` was created, according to the output:
> > 
> > ```
> > Migrations for 'feed':
> >   feed/migrations/0012_alter_post_prefernces.py
> >     - Alter field prefernces on post
> > ```
> > 
> > and the content of the `feed/migrations/0012_alter_post_prefernces.py` file is:
> > 
> > ```python
> > # Generated by Django 4.0.3 on 2022-03-30 06:32
> > 
> > from django.db import migrations, models
> > import django.db.models.deletion
> > 
> > 
> > class Migration(migrations.Migration):
> > 
> >     dependencies = [
> >         ('job_board', '0004_test_data_years_of_experiences'),
> >         ('feed', '0011_comments'),
> >     ]
> > 
> >     operations = [
> >         migrations.AlterField(
> >             model_name='post',
> >             name='prefernces',
> >             field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='job_board.preference'),
> >         ),
> >     ]
> > ```
> > 
> > Is this alright? Do you know this?
> 
> @taljacob2 thanks for letting me know.
> 
> That weird, Iv'e destroyed my VM and deleted the db file, the ran `vagrant up` but didn't got the output that you've got.
> Anyway I ran `pipenv run python manage.py makemigrations` and also got the same migration file as you did.
> I also ran `pipenv run python manage.py migrate` and everything seems to work find before and after this migration,
> I mean that I can see that the post model has the preference model linked to it via the admin panel before and after the migration.
> 
> I guess everything seems fine, and I'm wondering if this needs to be commited to repo, what are your thoughts about it?

I guess eventually we will add this file anyway because Django wants us to. Although I am not sure this file does anything essential. It is possible to decide about this in the future, and leave it like this for now.

**Pull request merged**
