### PR TITLE
🏇 Fill database - Posts

### LINKED ISSUE #156: 🏇 Fill database - Posts
- [x]  Add more job offers with the new locations and job types
- [x]  Add more looking for a job posts with the new job types

### PR DESCRIPTION
**Pull request by ShirleyFichman**
- [x] Added more posts to the database- both job offers and regular posts.
- [x] Updated tests accordingly.

Depending on #152
Close #156

### CODE REVIEW

**Comment by paOmer** [comment]
Looks good, could you please rebase so it would be easier to review the relevant parts only

**Review by DeanBiton — APPROVED** [review]
LGTM

**Review by Yarboa — COMMENTED** [review]
I would advise using json files instead of .py
try to have some ideas here 
https://www.geeksforgeeks.org/read-json-file-using-python/

WDYT?

**Comment by ShirleyFichman** [comment]
> I would advise using json files instead of .py try to have some ideas here https://www.geeksforgeeks.org/read-json-file-using-python/
> 
> WDYT?

I think it's the right use of json file so I changed accordingly

**Review by Yarboa — APPROVED** [review]
LGTM

**Pull request merged**
