### PR TITLE
🏇 Post Detail View: Button

### LINKED ISSUE #133: 🏇 Post Detail View: add a button
Add a button which lets the user to get to a specific post page.

### PR DESCRIPTION
**Pull request by paOmer**
Added a button to redirect a user to a specific post detail view.
The button located in each post title.
The relevant tests appear [here](https://github.com/redhat-beyond/JobSeeker/blob/0d0d256a9e529b195c068ac058d236c9f8aa830e/feed/tests/test_feed_views.py#L34-L54)
Close #133

### CODE REVIEW

**Review by DeanBiton — APPROVED** [review]
LGTM

**Review by amittcohen — APPROVED** [review]
LGTM

**Review by ShirleyFichman — APPROVED** [review]
LGTM

**Review by Yarboa — COMMENTED** [review]
@paOmer is there a test the covers this chnge? 
In case yes, please add reference to the code in the initial commit message

**Comment by paOmer** [comment]
> @paOmer is there a test the covers this chnge? In case yes, please add reference to the code in the initial commit message

There are test to cover this change, updated.
Also adding the link [here](https://github.com/redhat-beyond/JobSeeker/blob/0d0d256a9e529b195c068ac058d236c9f8aa830e/feed/tests/test_feed_views.py#L34-L54)

**Review by Yarboa — APPROVED** [review]
LGTM

**Pull request merged**
