### PR TITLE
:horse_racing: Login page: Indicating the user if it is already logged in

### PR DESCRIPTION
**Pull request by amittcohen**
In case a user is already logged in and tries to access the login page, instead of seeing the login form - it will get a message indicating that it is already logged in.

### CODE REVIEW

**Review by paOmer — APPROVED** [review]
LGTM, dont forget to rebase and push in order for the register link removal to be dropped from this PR

**Review by DeanBiton — CHANGES_REQUESTED** [review]
Create a test for a user trying this.

**Comment by Yarboa** [comment]
> Create a test for a user trying this.

+1. please modify login tests have some idea
https://github.com/redhat-beyond/beyond-tutorial/blob/main/msgboard/tests.py#L59

**Review by Yarboa — CHANGES_REQUESTED** [review]
see last comment related to tests

**Review by kasemAlem — COMMENTED** [review]
Is changes requested by @Yarboa is done ? 
please work on this PR

**Comment by amittcohen** [comment]
@Yarboa @kasemAlem Rebased to new form design

**Comment by Yarboa** [comment]
> @Yarboa @kasemAlem Rebased to new form design

@amittcohen 
Is there a test some where? to check logout?

**Comment by Yarboa** [comment]
> > @Yarboa @kasemAlem Rebased to new form design
> 
> @amittcohen Is there a test some where? to check logout?

There is a test here 
https://github.com/redhat-beyond/JobSeeker/blob/main/login/tests.py#L26

**Review by Yarboa — APPROVED** [review]

**Pull request merged**
