### PR TITLE
🏇 Improve Login Form Design Using crispy-forms

### LINKED ISSUE #90: 🚀  Crispy-Forms
Add crispy forms package to the project.
django-crispy-forms is a package that helps style forms in django easily.
Find more details [here](https://django-crispy-forms.readthedocs.io/en/latest/).

### LINKED ISSUE #117: 🏇 Login form: add some design
Currently, we have a pretty basic login form: 
Screenshot 2022-04-16 201424
There is a need to improve it's design for a better UI.

### PR DESCRIPTION
**Pull request by paOmer**
Improved login form design using django-crispy-form package.

django-crispy-forms is a package that helps style forms in django easily.
Find more details [here](https://django-crispy-forms.readthedocs.io/en/latest/).

- Installed the package
- Added the package to the installed apps list
- Set the package to use bootstrap 4
- Used crispy-forms on the login form

New login form screenshot:

Screen Shot 2022-04-17 at 20 18 07

Close #90 
Close #117

### CODE REVIEW

**Review by Yarboa — CHANGES_REQUESTED** [review]
Please suggest test that it is really working
Idea ti use client helper s fixture

**Comment by paOmer** [comment]
> Please suggest test that it is really working Idea ti use client helper s fixture

Hi @Yarboa, I cant figure out how or what exactly to check here, would appreciate further guidance here

**Review by amittcohen — APPROVED** [review]
LGTM

**Comment by Yarboa** [comment]
> > Please suggest test that it is really working Idea ti use client helper s fixture
> 
> Hi @Yarboa, I cant figure out how or what exactly to check here, would appreciate further guidance here

Why did you add crispy-form? add a form and test it works with crispy

**Comment by paOmer** [comment]
> > > Please suggest test that it is really working Idea ti use client helper s fixture
> > 
> > 
> > Hi @Yarboa, I cant figure out how or what exactly to check here, would appreciate further guidance here
> 
> Why did you add crispy-form? add a form and test it works with crispy

I have repurposed this PR to edit the login form along installing django-crispy-forms in order to have a form to test on.

I have tried to use the client fixture in order to test crispy, though couldn't find a way.
I tried the following:
`response = client.get("/login/")` and couldn't find any reference to crispy, not in `response.context` in general, and not in `response.context['form']` in specific.

I can offer a visual test:
- when not applying the crispy tag, meaning only mentioning `{{ form }}` in the `login.html` I get the following outcome:
Screen Shot 2022-04-17 at 20 32 34

- when applying {{ form.as_p }}, I get the following outcome:
Screen Shot 2022-04-17 at 20 33 51

- when applying the crispy tag `{{ form|crispy }}`, I get the following outcome:
Screen Shot 2022-04-17 at 20 18 07

**Review by DeanBiton — APPROVED** [review]
LGTM

**Review by ShirleyFichman — APPROVED** [review]
Looks very good! Approved

**Comment by Yarboa** [comment]
> > > > Please suggest test that it is really working Idea ti use client helper s fixture
> > > 
> > > 
> > > Hi @Yarboa, I cant figure out how or what exactly to check here, would appreciate further guidance here
> > 
> > 
> > Why did you add crispy-form? add a form and test it works with crispy
> 
> I have repurposed this PR to edit the login form along installing django-crispy-forms in order to have a form to test on.
> 
> I have tried to use the client fixture in order to test crispy, though couldn't find a way. I tried the following: `response = client.get("/login/")` and couldn't find any reference to crispy, not in `response.context` in general, and not in `response.context['form']` in specific.
> 
> I can offer a visual test:
> 
> * when not applying the crispy tag, meaning only mentioning `{{ form }}` in the `login.html` I get the following outcome:
>   Screen Shot 2022-04-17 at 20 32 34
> * when applying {{ form.as_p }}, I get the following outcome:
>   Screen Shot 2022-04-17 at 20 33 51
> * when applying the crispy tag `{{ form|crispy }}`, I get the following outcome:
>   Screen Shot 2022-04-17 at 20 18 07

try this
https://github.com/redhat-beyond/beyond-tutorial/blob/main/msgboard/tests.py#L25-L29

**Review by Yarboa — APPROVED** [review]

**Pull request merged**
