### PR TITLE
📝 Updating `README.md`

### LINKED ISSUE #19: 📝 Update `README.md`
We should update the main [README](https://github.com/redhat-beyond/JobSeeker/blob/main/README.md) with the following:

- [X] Replace the copied emojis with coded emojis,
       so that in case this markdown would be
       rendered in a different website than Github,
       then the emojis from Github would be replaced
       with the ones matching with the new website.

- [X] At the end of the "Run The Application" section:
       Indicate the URL that the Django web-application
       will be launched at.

- [x] Add a logo thumbnail to the top of the file.

### PR DESCRIPTION
**Pull request by taljacob2**
- Replaced the copied emojis with coded emojis,
  so that in case this markdown would be
  rendered in a different website than Github,
  then the emojis from Github would be replaced
  with the ones matching with the new website.

- At the end of the "Run The Application" section:
  Indicated the URL that the Django web-application
  will be launched at.

- Added a logo thumbnail to the top of the file.
  > You can use the logo too, from [here](https://svgur.com/s/fFV).

### You can view this file on my branch [here](https://github.com/taljacob2/JobSeeker/blob/doc/updating-main-readme/README.md).

Close #19 

Signed-off-by: Tal Jacob <taljacob2@gmail.com>

### CODE REVIEW

**Comment by taljacob2** [comment]
Changes are ready for review.

**Comment by paOmer** [comment]
Looks good and extensive @taljacob2 , maybe consider add our team members to the file

- [Tal Jacob](https://github.com/taljacob2)
- [Amit Cohen](https://github.com/amittcohen)
- [Dean Biton](https://github.com/DeanBiton)
- [Shirley Fichman](https://github.com/ShirleyFichman)
- [Omer Pahima](https://github.com/paOmer)

**Comment by taljacob2** [comment]
> Looks good and extensive @taljacob2 , maybe consider add our team members to the file
> 
> - [Tal Jacob](https://github.com/taljacob2)
> - [Amit Cohen](https://github.com/amittcohen)
> - [Dean Biton](https://github.com/DeanBiton)
> - [Shirley Fichman](https://github.com/ShirleyFichman)
> - [Omer Pahima](https://github.com/paOmer)

Will do.

**Comment by taljacob2** [comment]
> > Looks good and extensive @taljacob2 , maybe consider add our team members to the file
> > 
> > - [Tal Jacob](https://github.com/taljacob2)
> > - [Amit Cohen](https://github.com/amittcohen)
> > - [Dean Biton](https://github.com/DeanBiton)
> > - [Shirley Fichman](https://github.com/ShirleyFichman)
> > - [Omer Pahima](https://github.com/paOmer)
> 
> Will do. 

I can use your help here.
I have already prepared a "Team" section in the `CONTRIBUTING.md` in #16.

We should avoid duplicates. 

So should I link the `README.md` to the `CONTRIBUTING.md`'s "Teams" section? Or the other way around?

**Comment by taljacob2** [comment]
> > > > Looks good and extensive @taljacob2 , maybe consider add our team members to the file
> > > > 
> > > > * [Tal Jacob](https://github.com/taljacob2)
> > > > * [Amit Cohen](https://github.com/amittcohen)
> > > > * [Dean Biton](https://github.com/DeanBiton)
> > > > * [Shirley Fichman](https://github.com/ShirleyFichman)
> > > > * [Omer Pahima](https://github.com/paOmer)
> > > 
> > > 
> > > Will do.
> > 
> > I can use your help here. I have already prepared a "Team" section in the `CONTRIBUTING.md` in #16.
> > 
> > We should avoid duplicates.
> > 
> > So should I link the `README.md` to the `CONTRIBUTING.md`'s "Teams" section? Or the other way around?
> 
> I'm thinking to link the `CONTRIBUTING.md` to the `README.md` file and add "if you wish to contribute to our project, please follow along our `CONTRIBUTING.md` ", as the README file appears on the repo main page.

Okay. So to make sure I undertand:

- I will keep the "Teams" section in the `CONTRIBUTING.md`.
- I will create a link in the `README.md` to the "Teams" section in `CONTRIBUTING.md`?

**Comment by paOmer** [comment]
> > > > > Looks good and extensive @taljacob2 , maybe consider add our team members to the file
> > > > > 
> > > > > * [Tal Jacob](https://github.com/taljacob2)
> > > > > * [Amit Cohen](https://github.com/amittcohen)
> > > > > * [Dean Biton](https://github.com/DeanBiton)
> > > > > * [Shirley Fichman](https://github.com/ShirleyFichman)
> > > > > * [Omer Pahima](https://github.com/paOmer)
> > > > 
> > > > 
> > > > Will do.
> > > 
> > > 
> > > I can use your help here. I have already prepared a "Team" section in the `CONTRIBUTING.md` in #16.
> > > We should avoid duplicates.
> > > So should I link the `README.md` to the `CONTRIBUTING.md`'s "Teams" section? Or the other way around?
> > 
> > 
> > I'm thinking to link the `CONTRIBUTING.md` to the `README.md` file and add "if you wish to contribute to our project, please follow along our `CONTRIBUTING.md` ", as the README file appears on the repo main page.
> 
> Okay. So to make sure I understand:
> 
> * I will keep the "Teams" section in the `CONTRIBUTING.md`.
> * I will create a link in the `README.md` that refers to the "Teams" section in `CONTRIBUTING.md`?

Yeah, keep the "Teams" section in the `CONTRIBUTING.md`.
But, i'm thinking it's best to just mention the `CONTRIBUTING.md` in the `README.md` when referring to "if you wish to contribute to our project... " and just drop the part of referring regards to the team.
That just my thoughts on it...

**Comment by taljacob2** [comment]
> > > > > > Looks good and extensive @taljacob2 , maybe consider add our team members to the file
> > > > > > 
> > > > > > * [Tal Jacob](https://github.com/taljacob2)
> > > > > > * [Amit Cohen](https://github.com/amittcohen)
> > > > > > * [Dean Biton](https://github.com/DeanBiton)
> > > > > > * [Shirley Fichman](https://github.com/ShirleyFichman)
> > > > > > * [Omer Pahima](https://github.com/paOmer)
> > > > > 
> > > > > 
> > > > > Will do.
> > > > 
> > > > 
> > > > I can use your help here. I have already prepared a "Team" section in the `CONTRIBUTING.md` in #16.
> > > > We should avoid duplicates.
> > > > So should I link the `README.md` to the `CONTRIBUTING.md`'s "Teams" section? Or the other way around?
> > > 
> > > 
> > > I'm thinking to link the `CONTRIBUTING.md` to the `README.md` file and add "if you wish to contribute to our project, please follow along our `CONTRIBUTING.md` ", as the README file appears on the repo main page.
> > 
> > Okay. So to make sure I understand:
> > 
> > * I will keep the "Teams" section in the `CONTRIBUTING.md`.
> > * I will create a link in the `README.md` that refers to the "Teams" section in `CONTRIBUTING.md`?
> 
> Yeah, keep the "Teams" section in the `CONTRIBUTING.md`.
> But, i'm thinking it's best to just mention the `CONTRIBUTING.md` in the `README.md` when referring to "if you wish to contribute to our project... " and just drop the part of referring regards to the team.
> That just my thoughts on it...

I agree with you. Thanks for support :+1:

**Review by ShirleyFichman — APPROVED** [review]
Looks amazing and extensive as always, great job!

**Review by amittcohen — APPROVED** [review]
LGTM

**Review by Yarboa — COMMENTED** [review]
LGTM

**Pull request merged**
