### PR TITLE
:horse_racing: Update links in base template

### LINKED ISSUE #74: 🏇 Update Links In Base Template
The links to different pages in the base template need's to be updated to direct to the correct pages.
The base template located at `jobseeker/templates/jobseeker/base_template.html`.

The links to be updated are:

- Logo should direct to feed
- Home should direct to feed
- Jobs should direct to job board
- Login should direct to login page
- Register should be removed

### PR DESCRIPTION
**Pull request by amittcohen**
As per issue #74 , links in the base template were updated as follows:
- Home button redirects to feed
- Login button redirects to login
- Logo redirects to feed
- Profile button redirects to personal profile (only after logging in)
- Jobs button redirects to job board (dependant on #93 )

closes #74

### CODE REVIEW

**Comment by amittcohen** [comment]
Tests fail because this pull request depends on pull request #93

**Review by paOmer — APPROVED** [review]

**Comment by DeanBiton** [comment]
> Tests fail because this pull request depends on pull request #93

@amittcohen #93 has been merged.

**Comment by amittcohen** [comment]
> > Tests fail because this pull request depends on pull request #93
> 
> @amittcohen #93 has been merged.

Tests successful after merging #93.

**Review by DeanBiton — APPROVED** [review]

**Review by Yarboa — CHANGES_REQUESTED** [review]
Please make sure there are tests already in main repo covers your changes
If yes please share the tests.
If some are missing please add to your PR

**Comment by amittcohen** [comment]
> Please make sure there are tests already in main repo covers your changes If yes please share the tests. If some are missing please add to your PR

@Yarboa There are tests for entering each of the links I added.
For example, the test for the feed link can be found here: https://github.com/redhat-beyond/JobSeeker/blob/main/feed/tests/test_app_response.py

**Review by Yarboa — APPROVED** [review]

**Comment by Yarboa** [comment]
LGTM

**Pull request merged**
