### PR TITLE
🚀  Post: Delete View

### LINKED ISSUE #104: 🚀  Post: Delete View
Add an option to delete a post.
Make sure only the author of the post could delete it.

### PR DESCRIPTION
**Pull request by paOmer**
Adding an option for a user to delete a post.
Only the author of the post could delete it.
Used a DeleteView to create the desired view, edited the get_success_url function to return a success message with the new response, and to redirect the user to the feed.

Close #104

### CODE REVIEW

**Review by ShirleyFichman — APPROVED** [review]
Nicely done, approved

**Review by DeanBiton — APPROVED** [review]
@paOmer The PR looks good.
 A delete button should be added, you can add it in this PR or deal with it in another PR.

**Comment by paOmer** [comment]
> @paOmer The PR looks good. A delete button should be added, you can add it in this PR or deal with it in another PR.

@DeanBiton Will do in a new PR

**Comment by Yarboa** [comment]
Please rebase push

**Review by Yarboa — APPROVED** [review]

**Pull request merged**
